//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int ChildId { get; set; }
        public int IdParent { get; set; }
        public string ChildName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Tz { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
